src/main/java/org/lantern/SystemTrayImpl.java
src/main/java/org/lantern/http/InteractionServlet.java
src/main/java/org/lantern/state/SyncService.java

Changes to store browser name the UI is running in. This also includes updates to send an alert when the browser is Chrome and the UI is already open in an existing tab; otherwise, the UI is always opened in a new tab.

Issue 2095 - UI relays browser name

---

src/main/java/org/lantern/http/JettyLauncher.java

Note - this may not take effect until https://github.com/getlantern/lantern-ui/pull/79 is merged, which includes the client-side change to enable websockets.

#2193 Enabled websockets transport in CometD

---

Dockerfile
Makefile

This just more explicitly calls genassets when packaging, taking advantage of make's ability to optimize out redundant calls in the dependency tree (i.e. genassets won't get called multiple times when running ```make packages```, for example).

Explicitly generate assets when packaging closes #2431

---

src/github.com/getlantern/flashlight/genconfig/cloud.yaml.tmpl
src/github.com/getlantern/flashlight/genconfig/fallbacks.go.tmpl

Resolves #2440
We also need to run genconfig.bash again to mark all current servers as trusted. Trying…

use untrusted dialers if no trusted one available

---

Makefile
README.md

This PR adds a new target `release` that can be used to promote a beta version to a production release. `release` also pushes binaries that can be used by the auto-update server.
See https://github.com/getlantern/lantern/issues/2453

Adding "release" target and removing some responsabilities from "release-qa"

---

src/github.com/getlantern/detour/detour.go

Now the error message will look like:
> May 04 01:08:52.524 - detour: detour.go:139 Dial detoured to ssl.gstatic.com:443 failed: No dialers left

log detailed error if dialDetour() failed

---

src/github.com/getlantern/flashlight/statserver/peer.go
src/github.com/getlantern/geolookup/geolookup.go

`retryWait` was producing small values and error reporting was incomplete.
This could help fixing https://github.com/getlantern/lantern/issues/2394

Adjusting error threshold in peer geolocation.

---

src/github.com/getlantern/flashlight/config/config.go

This is related to the error fetching ``cloud.yaml`` we've been seeing for a long time in Loggly. The ``resp.Body.Close() `` is insufficient, and we need to explicitly indicate the request should be closed after we finish reading the response body. More details here: https://stackoverflow.com/questions/17714494/golang-http-request-results-in-eof-errors-when-making-multiple-requests-successi

add fix for https://github.com/getlantern/lantern/issues/2402

---

src/github.com/getlantern/flashlight/geolookup/geolookup.go
src/github.com/getlantern/flashlight/statserver/peer.go

The log we just merged from https://github.com/getlantern/lantern/pull/2474 was like below
> May 06 01:59:32.616 - flashlight.statserver: peer.go:106 Failed geolocation attempt 9/9: "Could not get response from server: \"Get http://geo.getiantem.org/lookup/178.62.198.216: net/http: request canceled while waiting for connection\"". Waiting 4m16s before retrying.
It would be better to revise it a bit as
1. it results different message groups on Loggly, as the waiting time varies;
2. quotation mark and backslash makes the text a bit clutter.
@xiam How do you think?

adjust log format in statserver/peer.go

---

src/github.com/getlantern/flashlight/config/config.go
src/github.com/getlantern/flashlight/flashlight.go
src/github.com/getlantern/flashlight/statserver/peer.go
src/github.com/getlantern/flashlight/statserver/statserver.go
src/github.com/getlantern/fronted/dialer.go
src/github.com/getlantern/fronted/fronted_test.go
src/github.com/getlantern/lantern-android/client/client.go
src/github.com/getlantern/lantern-android/client/client_test.go
src/github.com/getlantern/lantern-android/client/config.go
src/github.com/getlantern/lantern-android/client/config_test.go

@myleshorton : I think the only really necessary thing that the withclient scheme did was to clean up the extra fronted.Dialers that we were creating for direct domain fronting, as a result of extracting 'HighestQOSFrontedDialer'.  If we leave that logic at the balancer, the balancer takes care of cleaning those up alright.  
This PR makes a smaller change, while cherry picking all the useful things that came up while working on #2520 and #2529, as per: 
https://github.com/getlantern/lantern/pull/2529#issuecomment-102879786
I also made the commits tidier so they make it easier to understand the changes.  I think it will be faster to review this if you read the individual commits.

Fetch config via direct domain fronting, fixes #2520

---

src/github.com/getlantern/flashlight/ui/ui.go

Fixes https://github.com/getlantern/lantern/issues/2513
`ui.Start()` runs `http.Server` in separate goroutine, if that goroutine didn't get chance to run before `ui.Show()`, this issue will happen.
`WaitForServer()` for at most 3 seconds to resolve it.

ui.Show() wait for url in a go routine closes #2513

---

src/github.com/getlantern/flashlight/genconfig/proxiedsites/original.txt

This doesn't fully close out the issue but at least adds these to the list.

adding heroku and loggly to proxied sites list #2482

---

src/github.com/getlantern/flashlight/util/http.go

Hello @atavism, @myleshorton, this is a suggested fix for https://github.com/getlantern/lantern/pull/2541, I think it would be better to handle the waitforserver call inside the proxy creation routine, could you give it a look?

Adding waitforserver when creating HTTP proxy client.

---

Makefile

This should fix problems we were having by trying to build against the unstable golang/mobile repo.
See https://github.com/getlantern/lantern/issues/2552
In order to fully test this remove the golang/mobile docker image: `docker rmi -f golang/mobile` and try to create the Android's libjni

Issue 2552

---

src/github.com/getlantern/flashlight/config/config.go
src/github.com/getlantern/fronted/dialer.go

- Copy over the headers of direct fronted requests.
- Change to proprietary headers for caching, so CDNs and middleware
will hopefully keep their dirty hands off them.
These won't take effect until we deploy the config server, but in the meanwhile they won't make things any more broken either.

fix client side of #2568

---

src/github.com/getlantern/flashlight/README.md
src/github.com/getlantern/flashlight/genconfig/cfg2redis.py

This adds a semi-manual way to update the configuration in the redis database that [the config server](https://github.com/getlantern/config-server) uses.
Soon(TM), servers will register themselves when they come up.  At the moment, launching servers in Tokyo is still a semi-manual process, so that would need be fixed first.
As soon as we officially stop supporting client versions that rely on static `cloud.yaml`s we may do a more aggressive rewrite of this whole system, to simplify it.

add script to update the redis config from a cloud.yaml

---

src/github.com/getlantern/detour/detour.go
src/github.com/getlantern/flashlight/client/handler.go

It is too simple to believe, but we just closed wrong connections. `io.Copy` will not return if there's nothing to read from `connOut` unless we close it. Though we should dig more into why `idletiming` doesn't cause `connOut.Read()` to return.
To verify, run below command at any time to see if the ingress and egress connection count equals.
```
PID=`ps -ef | grep lantern | grep -v grep | cut -d " " -f 4` && lsof -nPp $PID | grep TCP | grep "8787->" | grep EST | wc && lsof -nPp $PID | grep TCP | grep ":443 (ESTABLISHED)" | wc
```

close both clientConn and connOut to resolve #2330

---

src/github.com/getlantern/flashlight/config/config.go

This is a quick fix just in case https://github.com/getlantern/lantern/issues/2390 doesn't make it to next release.

make config updates replace, instead of appending to, TrustedCAs. fixes #2612

---

src/github.com/getlantern/fronted/dialer.go

I don't think this one is particularly consequential in practice, but we generally want to make sure these DDF connections are closed as well. Mind taking a peek @aranhoide?

Add tls handshake timeout and don't keep connections alive closes #2614

---

src/github.com/getlantern/fronted/masquerade.go

This may help us decide if [this error](https://github.com/getlantern/lantern/issues/2398) is really that bad.

Forcing extended log

---

Makefile
src/github.com/getlantern/flashlight/flashlight.go
src/github.com/getlantern/flashlight/logging/logging.go
src/github.com/getlantern/lantern-android/client/client.go
src/github.com/getlantern/lantern-android/client/config.go
src/github.com/getlantern/lantern-android/libflashlight/make.bash

Some refactoring to use loggly from lantern-android.
Note: We're using a separate customer token for FireTweet in Loggly to delineate messages.

Add Loggly setup to lantern-android

---

Makefile

The Makefile will now run `genconfig` when preparing for a QA release.
Closes #2663

Adding a genconfig target to the Makefile

---

installer-resources/linux/lantern.sh

Added a verification that checks whether the system's Lantern binary got changed and replaces the user's copy of the binary in such case. 
See #2670.

When the system's Lantern binary is changed (on Linux) use it instead of the copy

---

src/github.com/getlantern/detour/detect.go
src/github.com/getlantern/detour/detour_test.go

Now if we use fake DNS to point any site to 127.0.0.1, detour will work.
`lantern.log:Jun 18 01:53:41.667 - DEBUG detour: detour.go:136 Dial initially to gmail.com:443 failed, try detour: dial tcp 127.0.0.1:443: connection refused`

Detour detect ECONNREFUSED to resolve #2638

---

Makefile

Simple fix, just relying on gomobile's updates. Additionally, the double-patch trick is not necessary any longer.

Fix for issue-2682

---

src/github.com/getlantern/flashlight/ui/ui.go

@myleshorton This will make sure the Manoto page only opens a single time and not when we click "Show Lantern"

Only open Manoto page once

---

src/github.com/getlantern/flashlight/flashlight.go
src/github.com/getlantern/flashlight/ui/ui.go

I'm not 100% sure why it seems to fix the issue, but this change removes a race condition on startup that could make the following sequence run in almost any order:
1. Lantern UI server port comes up
1. Lantern opens browser
1. Lantern proxy server comes up
1. Lantern sets the system proxy
My theory is that IE can get confused in some cases depending on the actual order those steps get executed, and in all my testing this change fixes the problem and ensures those steps always proceed as follows:
1. Lantern UI server port comes up
1. Lantern proxy server comes up
1. Lantern sets the system proxy
1. Lantern opens browser

Gets rid of race condition on startup closes #2719

---

src/github.com/getlantern/flashlight/config/config.go

This allows fronted servers to proxy http traffic if chained servers are blocked.

Make fronted servers trusted by default closes #2737

---

src/github.com/getlantern/flashlight/config/config.go
src/github.com/getlantern/flashlight/flashlight.go

This just adds the Lantern version to the yaml config file name on disk. That prevents Lantern from ever reading config files from old versions, which I think is exactly what we want.

Adding version to config file name closes #2731

---

src/github.com/getlantern/balancer/dialer.go

This just bumps up the timeouts for checks after failures as the existing timeouts otherwise look OK.

Bumped up timeout for checks closes #2743

---

src/github.com/getlantern/fronted/dialer.go
src/github.com/getlantern/fronted/masquerade.go

I think we don't need `tlsInfo()` anymore.

Removing tlsInfo() to keep logs clean and short.

---

src/github.com/getlantern/lantern-ui/app/index.html

This fixes the "Close Window" button that appears in the UI when the Lantern backend goes away.

Fix "Close Window" button

---

Makefile

Our Makefile was failing on Linux, see: https://github.com/getlantern/lantern/issues/2760

Fixing REVISION_DATE on Linux.

---

src/github.com/getlantern/tlsdialer/tlsdialer_test.go

TLSDialer test: make sure the error is of type net.Error before checking whether is a timeout error
https://github.com/getlantern/lantern/issues/2703

Fix for 2703

---

Makefile

At the end of the `make android-lib` I got this message:
```
FIRETWEET_MAIN_DIR environment variable: directory does not exist
```
Documentation says:
> If you pass the FIRETWEET_MAIN_DIR env variable to make android-lib, the generated bindings and library will be copied into it:
I didn't pass the variable, I just have my `FIRETWEET_MAIN_DIR` in another location.
I think the message is a bit confusing, it *sounds* like an error, but it isn't. @uaalto What do you think of this new message?
```
Either no FIRETWEET_MAIN_DIR variable was passed or the given value is not a
directory. You'll have to copy the .arr file manually:
cp -v src/github.com/getlantern/lantern-mobile/libflashlight.aar $FIRETWEET_MAIN_DIR
```

Rewriting the warning message to sound less like an error.

---

src/github.com/getlantern/flashlight/pac.go

Resolves https://github.com/getlantern/lantern/issues/2780
To exam ports, we have to match url with regex, which is error prone and [never perfect](https://mathiasbynens.be/demo/url-regex). It's rare to access non-standard ports on Internet, so I just skip it.

not proxy traffic to LAN hosts

---

src/github.com/getlantern/flashlight/flashlight.go

Note this doesn't address the actual issue in #2813 but rather temporarily disables localdiscovery so we can release 2.0.0 without worrying about this issue.

Temporarily disable localdiscovery #2813

---

src/github.com/getlantern/enproxy/proxy.go

This combined with more detailed client side logging should help narrow down some of these issues.

Adding more detailed error info in response bodies closes #2822

---

Makefile

package build for ARM wasn't forcing headless mode.

Fixes #2829

---

src/github.com/getlantern/flashlight/flashlight.go
src/github.com/getlantern/flashlight/ui/ui.go

This is a fairly big issue in terms of user experience because currently if Lantern is already running, users who double click on the desktop icon or select Lantern in the start menu experience nothing happening --- makes Lantern seem super broken.

Trigger an existing lantern to open the UI closes #2838

---

src/github.com/getlantern/flashlight/flashlight.go

See https://github.com/getlantern/lantern/issues/2840

Stopping Lantern when port 8787 is not available. Closes #2840

---

installer-resources/windows/lantern.nsi
src/github.com/getlantern/flashlight/flashlight.go
src/github.com/getlantern/launcher/launcher_windows.go

This is a workaround that relies on Lantern running at Windows start up with an specific flag that was introduced only to clear system proxy settings.
See #2776

Adding -clear-proxy-settings as workaround for #2776

---

src/github.com/getlantern/peerscanner/host.go

Temporarily disable registering and unregistering CloudFront (and therefore DNSimple) entries in peerscanner.

disable CloudFront/DNSimple support

---

src/github.com/getlantern/flashlight/server/server.go

Fixes #2539.
If `registerat` flag was empty, this would busy wait forever, hogging one CPU.

sleep unconditionally on every iteration of register loop

---

src/github.com/getlantern/flashlight/flashlight.go
src/github.com/getlantern/flashlight/server/server.go

Fixes #2395.  I tested this by deploying a binary built from this to one of our flashlight servers.  I got evidence that some hitherto banned countries were allowed, like Thailand:
Aug  6 04:25:02 fl-nl-20150226-010 flashlight: Aug 06 04:25:02.809 - 0m54s DEBUG flashlight.statreporter: statreporter.go:252 Reported {"dims":{"country":"TH"},"increments":{"bytesGivenTo":439,"bytesGivenToByFlashlight":439},"multiMembers":{"distinctClients":["180.183.148.247"],"distinctDestHosts":["www.google.com"]}} to statshub
But that PH was still banned:
Aug  6 04:25:43 fl-nl-20150226-010 flashlight: Aug 06 04:25:43.142 - 1m34s ERROR enproxy: proxy.go:358 Origin country not allowed: Not accepting connections from country PH

filter countries by blacklist, not whitelist

---

src/github.com/getlantern/tlsdialer/tlsdialer_test.go

Closes #2858 
I've run the tests on Travis 5 times. This error is not easily reproducible, it is a matter of times run. In case it fails again, we will reduce the timeout from 5000 microseconds to something like 3000-4000. But if it works with this tweak, is best to keep it at 5000.

Provide TLS Config to failing tests that randomly reach handshaking and fail unproperly

---

src/github.com/getlantern/flashlight/logging/logging.go
src/github.com/getlantern/wfilter/wfilter.go
src/github.com/getlantern/wfilter/wfilter_test.go

Prepend timestamp only on first line of a multiline output

---

src/github.com/getlantern/flashlight/flashlight.go

Fixes https://github.com/getlantern/lantern/issues/2934
Useful in headless mode.

add log when signal received

---

src/github.com/getlantern/flashlight/client/handler.go
src/github.com/getlantern/flashlight/logging/logging.go
src/github.com/getlantern/flashlight/logging/useragents.go

Register and report User-Agents used in Lantern session

---

src/github.com/getlantern/tlsdialer/tlsdialer_test.go

Closes #2968 
Adapts the test to reduce the timeout within a lower boundary to keep it reasonable. Without this, the test depend on the system, which will require continuous tuning and/or complicate reproducibility.

Add exponential backoff timeout to test

---

Makefile

Can you take a peek at this @xiam? I saw a weird panic in 2.0.1 on OSX that looked like it shouldn't have happened with a full rebuild.

Add -a flag to all go build calls to force a full rebuild closes #2974

---

src/github.com/getlantern/flashlight/client/handler.go

Can you also take a look at this one @uaalto?

don't try to respond with bad gateway after OK closes #2977

---

src/github.com/getlantern/flashlight/client/handler.go

You mind taking a look at this one too @uaalto? This should be easily reproducible on valencia with just go build -race

Data race in handler.go error variable itself closes #2981

---

src/github.com/getlantern/flashlight/statserver/peer.go

Cleaning up data races in peer stats closes #2980

---

src/github.com/getlantern/flashlight/config/config.go

Slightly less risky version of this change.

Add cache control header and fix storing of etag closes #3076

---

src/github.com/getlantern/detour/detour.go

Closes #3086 
This bug was discovered as part of the on-going investigation for https://github.com/getlantern/lantern/issues/3077.
The rationale can be found here: https://golang.org/pkg/sync/atomic/#pkg-note-BUG

Fix atomic uint64 alignment issue that occurs on x86-32 and ARM

---

src/github.com/getlantern/flashlight/flashlight.go

Issue #3077 is confirmed to be triggered by panicwrap trying to fork a GUI app. This seems to offend Windows XP, due to invalid standard file descriptors. Unfortunately we didn't see any log of this because panicwrap fails before logging is configured. Additionally, this bug isn't detected because it doesn't happen if the application is run in console mode (which is generally used for development).
A better solution could be researched further, although I'm not certain it is viable yet, but I wanted to get this ASAP in valencia, since it could potentially affect all Windows XP users.

[important] Workaround for issue #3077

---

src/github.com/getlantern/balancer/balancer.go
src/github.com/getlantern/balancer/dialer.go

It's another small fix  in addition to yours @myleshorton to prevent "No dialers left to try" error when only 1 dialer available.

balancer: not exclude used dialers when retry

---

src/github.com/getlantern/flashlight/config/config.go

Do you think it's ok to merge to `release-2.0.1`, or `valencia` instead @myleshorton? This fixes the issue of only picking first chained server if more than one available during bootstrap.

iterate through bootstrap chained servers

---

src/github.com/getlantern/checkfallbacks/checkfallbacks.go

I did just to be able to use checkfallbacks as a tool for testing ATS. Could you take a look when you have time @fffw or @aranhoide ? (This is definitely not urgent/important).
It's just optionally showing the req/resp in the output, should be harmless.
Also, I've tried several tools (wget, curl, httpie). They all fail because the either don't support TLS connections to the proxy, nor setting headers for the proxy request.

Optional verbose output for checkfallbacks (useful for testing ATS)

---

src/github.com/getlantern/checkfallbacks/checkfallbacks.go

If there is an error in either req or resp, they are nil.

Fix issue in checkfallbacks

---

README.md

this adds a badge link to the ProjectTalk message board for lantern.
i think this could help make the issues more useful by moving a lot of the discussion that is not development related to the message board.
additionally you can use the "Moved to ProjectTalk" label on issues that should be discussed outside of github. those will automatically get imported to ProjectTalk and a comment with a link will be posted to the issue.

add projecttalk link

---

src/github.com/getlantern/checkfallbacks/checkfallbacks.go
src/github.com/getlantern/checkfallbacks/verify.go

Fixes https://github.com/getlantern/lantern/issues/3179
This new option can be used to verify the functionality of ATS based chained server. Currently it only checks https://github.com/getlantern/lantern/issues/3133 and https://github.com/getlantern/lantern/issues/3147, but we can add more checks later.

add -verify option to checkfallbacks fix #3179

---

src/github.com/getlantern/systray/systray.go
src/github.com/getlantern/systray/systray_darwin.m
src/github.com/getlantern/systray/systray_nonwindows.go

It's a rather quick fix to https://github.com/getlantern/lantern/issues/3246
As per [doc](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Miscellaneous/Foundation_Functions/index.html#//apple_ref/c/func/NSDefaultMallocZone)
> Zones are ignored on iOS and 64-bit runtime on OS X. You should not use zones in current development.
So it's safe to run on any supported OS X versions.
@myleshorton mind take a look?

remove deprecated menuZone from systray

---

.travis.yml
Dockerfile
Makefile
src/github.com/getlantern/lantern-mobile/Dockerfile

Closes #3194 
Those changes in the LDFLAGS are due to a deprecation notice and future removal for the old args syntax.

Go version bump (security fix) -> 1.4.3

---

src/github.com/getlantern/flashlight/client/reverseproxy.go
src/github.com/getlantern/flashlight/config/config.go
src/github.com/getlantern/flashlight/flashlight_test.go
src/github.com/getlantern/geolookup/geolookup.go

Resolves #3330 to eliminate those weird meaningless Loggly entries.
@xiam mind take a look? It's a slight change to `errorRewritingRoundTripper`. Changes to `flashlight_test.go` are simply making `go vet` happy.
By requesting an inexist port with different user agent via Lantern, we can see the effect.
`curl -vLx localhost:8787 http://twitter.com:8000`
`curl -vLx localhost:8787 http://twitter.com:8000  -H "User-Agent: Mozilla/5.0"`

only render error page to browsers

---

Makefile

Hey @xiam this change should work.
```
> otool -l ./lantern_darwin_amd64  | grep -A 3 LC_VERSION_MIN_MACOSX
cmd LC_VERSION_MIN_MACOSX
cmdsize 16
version 10.7
sdk 10.11
```
`man clang` gives me the clue. golang doesn't recognize `-mmacosx-version-min` as CGO hint. Fortunately environment variable works.
```
MACOSX_DEPLOYMENT_TARGET
If -mmacosx-version-min is unspecified, the default deployment target is read from this environment variable.  This option only affects darwin
targets.
```

support minimum OSX 10.7

---

src/github.com/getlantern/lantern-mobile/app/src/main/AndroidManifest.xml
src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/activity/LanternMainActivity.java
src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/model/UI.java
src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/sdk/Utils.java
src/github.com/getlantern/lantern-mobile/lantern/interface.go

This registers a new broadcast receiver that detects changes in network connectivity. If Lantern is running, and we disconnect from Wi-Fi, we automatically turn off the VPN service.

Stop Lantern when user disconnects from WiFi network

---

Makefile
src/github.com/getlantern/flashlight/flashlight.go
src/github.com/getlantern/flashlight/main/autoupdate.go

This addresses the issue with production builds not running.  As a bonus, it no longer relies on text substitution and instead uses Go linker flags.

Fixed setting of PackageVersion in production builds

---

src/github.com/getlantern/eventual/eventual.go

closes getlantern/lantern#3551
One can verify this by running `go test -race` in the eventual package.

Fixed data race in eventual

---

src/github.com/getlantern/flashlight/logging/logging.go

It's a rather simple change to show client errors in separate source group.

add logglyTag

---

src/github.com/getlantern/flashlight/genconfig/proxiedsites/original.txt

About as simple as a changelog itself can be, but it would be useful to review the underlying thinking here. I basically noticed in our logs that detour was dynamically determining what to do with getiantem.org

adding getiantem.org closes #3638

---

Makefile
README-release.md
README.md

This breaks out the release details from the README @xiam and @oxtoacart since that only applies to Lantern developers actually creating releases and goes into detail that's unusual for a Makefile. I also added simple instructions for building "the old fashioned way" with just `go build`. Finally, I added back the `make docker` target in the Makefile.

README and Makefile cleanups

---

src/github.com/getlantern/idletiming/idletiming_conn.go

In https://golang.org/pkg/net/#Conn
> // A zero value for t means I/O operations will not time out.

idletiming correctly set deadline fix #3866

---

src/github.com/getlantern/flashlight/flashlight.go
src/github.com/getlantern/flashlight/main/main.go

This gets rid of the transitive mobile -> proxied sites -> ui dependency.
@myleshorton This undoes what you did here - https://github.com/getlantern/lantern/commit/e73ca0dd1bbe2f5f376c111a9a5cdb0ec7b96f73#diff-f51f873318b593f0a492e1abb11a57c2R149  What was the reason for that initial change?  Will it cause any problems to go back to just configuring proxiedsites in main?

Configuring proxiedsites in main instead of flashlight, removes ui as dependency for mobile

---

src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/activity/LanternMainActivity.java
src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/model/UI.java
src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/vpn/Service.java

This resolves #3708 and https://github.com/getlantern/lantern/issues/3711 ... re-opening since I accidentally merged this in already.
A few test cases: 
- Leave Lantern running, forcibly stop the app from the Application Manager, and verify the button is turned OFF when the app is re-opened. 
- Leave Lantern turned ON, close the app normally, and verify Lantern stays running in the background.

Clear shared preferences when Lantern is first run

---

src/github.com/getlantern/lantern-mobile/app/src/main/res/layout/activity_lantern_main.xml

To resolve https://github.com/getlantern/lantern/issues/4040, a quick fix to center the on/off toggle button inside the parent layout using the ``layout_centerHorizontal`` attribute instead of w/ any left padding.

Issue 4040

---

MobileSDK/sdk/build.gradle
PubSub/sdk/build.gradle
README.md
src/github.com/getlantern/lantern-mobile/build.gradle

In order to be able to compile Lantern for Android, I had to specify the build tools revision to the latest.
Unfortunately I couldn't find a method to wildcard the build tools revision so it doesn't need to be updated manually. I also cannot find revision 2, so I had no other option than to update. In case you had it working already, this steps for updating the revision might be of reference.
`android list sdk -a`
Shows a list:
1- Android SDK Tools, revision 24.0.2
2- Android SDK Platform-tools, revision 21
3- Android SDK Build-tools, revision 21.1.2
...
Select using ID for build-tools 23.0.3
`android update sdk -a -u -t 3`

Update build tools revision and Readme (Android)

---

src/github.com/getlantern/lantern-mobile/app/src/main/res/layout/feed_item.xml
src/github.com/getlantern/lantern/feed.go

Whenever an article is missing a meta description tag, use the content entry instead. This also fixes https://github.com/getlantern/lantern/issues/4049

Use content when meta description unavailable

---

src/github.com/getlantern/lantern-ui/app/partials/error.html

@myleshorton Simple change to fix https://github.com/getlantern/lantern/issues/4108

hide error page when showing mobile ad fix #4108

---

src/github.com/getlantern/lantern-ui/app/partials/feeds.html
src/github.com/getlantern/lantern/feed.go
src/github.com/getlantern/lantern/feed_test.go

Depends on getlantern/everfeed-combiner#18

Excluding feeds from all based on excludeFromAll property

---

src/github.com/getlantern/flashlight/feed/feed.go

This fixes a tiny discrepancy between desktop and mobile. Whenever an article meta description is missing, we use ``contentSnippetText`` instead of ``contentText`` now. The former field is the one updated by the feed server already to provide article descriptions for sites like Reddit.

Issue 4109

---

src/github.com/getlantern/flashlight/client/handler.go
src/github.com/getlantern/flashlight/logging/useragents.go
src/github.com/getlantern/flashlight/util/http.go

@myleshorton It should be worth to add to 2.2.0. With this patch, no any `CLOSE` or `CLOSE_WAIT` seen after running for 10min, while previously, at least 2 will be seen in a few seconds.

close response body when bad status code fix #3987

---

.travis.yml
Makefile
README.md
setenv.bash

Hey @oxtoacart, I initially could not make the thing work, I had to make a few changes, could you take a look at them?

Few fixes for building on Windows.

---

src/github.com/getlantern/flashlight/main/pac.go

See https://github.com/getlantern/lantern/pull/4212

Adds a parameter to prevent the PAC URL from being cached by Windows (release-2.2.0)

---

src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/activity/LanternMainActivity.java

This resolves https://github.com/getlantern/lantern/issues/4226 -- to prevent the on/off switch from being toggled continuously, we disable the switch temporarily while the VpnService updates the connection.

Add back code for disabling ON/OFF switch temporarily

---

src/github.com/getlantern/flashlight/main/pac.go

Hey @myleshorton, this implements your suggestion of changing the pac URL everytime it is set, this effectively forces a reset, even on Windows. It looks like problems with Xunlei get somewhat _fixed_ after  resetting the pac file, users may trigger a reset by themselves with checking/unchecking the proxy all feature. On my experience, though, I had no problems with Xunlei 7.9 and latest QA version, only with [Xunlei 5 + IE](https://support.microsoft.com/en-us/kb/2520403) and current public beta.

Changing no-cache argument everytime we set the PAC URL.

---

Makefile

A requirement for https://github.com/getlantern/lantern/issues/3797, this updates the Makefile to also include Android when we publish our releases to GitHub. Already added 2.2.3 [here](https://github.com/getlantern/lantern/releases/tag/2.2.3)

Add package-android to Makefile

---

src/github.com/getlantern/flashlight/proxiedsites/proxiedsites.go

We no longer show or modify proxied sites in UI. Remove relevant code.
It may also helpful for https://github.com/getlantern/lantern/issues/4282. Though we don't exactly know the cause, but inspired by [this SO link](http://stackoverflow.com/questions/31265789/websocket-invalid-frame-header), a large WebSocket frame may trigger "Invalid frame header" error if browser/server has some bug handle it.
@xiam Mind have a look?

not serving proxied sites to ui

---

src/github.com/getlantern/flashlight/client/client.go
src/github.com/getlantern/flashlight/client/dial_direct.go
src/github.com/getlantern/flashlight/client/dial_direct_android.go
src/github.com/getlantern/protected/protected.go

@oxtoacart It's an attempt to avoid the SOCKS5 change from failing on Windows.

flashlight client call protect package only on Android

---

lantern-ui/app/js/services.js
src/github.com/getlantern/bandwidth/bandwidth.go
src/github.com/getlantern/bandwidth/bandwidth_test.go
src/github.com/getlantern/chained/dialer.go
src/github.com/getlantern/flashlight/app/app.go
src/github.com/getlantern/flashlight/app/bandwidth.go
src/github.com/getlantern/flashlight/app/settings.go
src/github.com/getlantern/flashlight/client/client.go
src/github.com/getlantern/flashlight/client/reverseproxy.go
src/github.com/getlantern/flashlight/ui/service.go
testpackages.txt

In order to test this, you can locally run a proxy that spits out fake bandwidth tracking stats by building from https://github.com/getlantern/http-proxy-lantern/tree/throttling-ox

Dynamic bandwidth tracking

---

src/github.com/getlantern/balancer/balancer.go
src/github.com/getlantern/flashlight/client/client.go
src/github.com/getlantern/flashlight/config/config.go
src/github.com/getlantern/flashlight/config/fetcher.go

I noticed that we didn't update the config server whitelisting code when we added the staging flag.  This fixes that.

Whitelisting staging config URL

---

src/github.com/getlantern/flashlight/proxied/proxied.go
src/github.com/getlantern/fronted/direct.go

With all these http.Transports that we're creating, we missed a few opportunities to cache TLS sessions, which results in unnecessary handshaking/load to servers.
This probably won't have a huge impact since it's mostly used for our internal polling stuff, but it can't hurt.

Added TLS ClientSessionCache in a few places to reduce TLS handshaking

---

src/github.com/getlantern/balancer/dialer.go
src/github.com/getlantern/fdcount/fdcount_test.go

I noticed a lot of log output from the balancer test and saw that the default check function returns false.  That creates unnecessary work since it triggers a recheck, and that recheck can never succeed because the default check function will always return false.

When no check function provided for dialer, return true

---

src/github.com/getlantern/balancer/balancer.go
src/github.com/getlantern/balancer/balancer_test.go

It uses `SwapInt64` to avoid `checkDialers` from running multiple times when `balancer.Dial` is called simultaneously.
@oxtoacart want to have a look again?

check dialers only once after idle

---

Makefile
src/github.com/getlantern/balancer/balancer_test.go

Since I was in the Makefile, I took care of a couple of pet peeves of mine:
1. test target now runs in about 45 seconds instead of several minutes
2. resources.go is no longer regenerated everytime I build lantern
3. lantern is automatically rebuilt if any of the non-test go source files changed

Speed up builds

---

Makefile
src/github.com/getlantern/flashlight/app/autoupdate.go
src/github.com/getlantern/flashlight/app/mock_autoupdate.go

This is the client part required to [stage autoupdates](https://github.com/getlantern/autoupdate-server/pull/2).

Add support for simulating autoupdates locally.

---

src/github.com/getlantern/balancer/balancer.go

It cherry-picks the commit in https://github.com/getlantern/lantern-pro/pull/73. That PR was created to wrong repo.

align balancer.lastDialTime in 64bit boundary

---

src/github.com/getlantern/errors/errors.go
src/github.com/getlantern/errors/errors_test.go
src/github.com/getlantern/golog/golog.go
src/github.com/getlantern/golog/golog_test.go

It intends to fix https://github.com/getlantern/lantern/issues/4803 indirectly by replacing `MultiLine` with a more direct one pass `PrintStack`.
There's one slight difference of `golog` output: The file/line number prepended to each line of stacktrace is removed. Actually, it's what I wanted to remove!
I do want to solve the interleaving of log lines in this PR.

Simplify golog and errors package by calling PrintStack directly

---

README.md

Removed the country tags (`cn`, `gb`, etc) from the language headers to prevent flag icon rendering.
Added Persian and Arabic language section links at the top of the page.

remove country tags, add Persian, Arabic section links
