getlantern/lantern

src/main/java/org/lantern/proxy/pt/BasePluggableTransport.java, src/main/java/org/lantern/proxy/pt/FlashlightServerManager.java, src/test/resources/log4j.properties
Considering this as a hotfix for master.
=> Issue 2164

src/main/java/org/lantern/multicast/LanternMulticast.java, src/main/java/org/lantern/state/StaticSettings.java
@atavism I realized in testing your changes I was pointing to the totally wrong host! Should be fixed with this PR.
=> changed to use network endpoint #2188

install/osx/configureOsx.bash
Resolves https://github.com/getlantern/lantern/issues/2112
=> chown launchd plist file to current user

.gitignore, Makefile
Some quick fixes after our repository migration.
=> Few fixes for brand consistency

src/github.com/getlantern/lantern-ui/app/js/app.js, src/github.com/getlantern/lantern-ui/dist/js/app.js
Just re-creating on behalf of @atavism from flashlight-build
=> This fixes the issue reported here: getlantern/lantern#2373

Makefile
Adding missing docker dependencies.
=> Adding docker dependency.

src/github.com/getlantern/flashlight/client/handler.go
Resolves #2330. There will be no CLOSE_WAIT connections left.
I tried use `idletiming` instead of close immediately, but caused more CLOSE_WAIT state connection. Might worth digging into it but I guess the current way is enough.
=> force closing connection if request sent

Makefile
You mind glancing at this @xiam?
=> Removed -q option closes #2442

src/github.com/getlantern/flashlight/client/client.go, src/github.com/getlantern/flashlight/client/reverseproxy.go, src/github.com/getlantern/flashlight/ui/ui.go, src/github.com/getlantern/golog/golog.go, src/github.com/getlantern/golog/golog_test.go
=> golog can act as a std logger

src/github.com/getlantern/autoupdate-server/README.md, src/github.com/getlantern/autoupdate-server/main.go, src/github.com/getlantern/autoupdate-server/server/bindiff.go, src/github.com/getlantern/autoupdate-server/server/github.go, src/github.com/getlantern/autoupdate-server/server/github_test.go, src/github.com/getlantern/autoupdate-server/server/server.go
See https://github.com/getlantern/lantern/issues/2450
=> Better log messages for auto-update server.

src/github.com/getlantern/analytics/analytics.go, src/github.com/getlantern/lantern-android/client/client.go, src/github.com/getlantern/lantern-android/libflashlight/bindings/main.go
Changes to support different analytics tracking codes for each lantern android app, related to https://github.com/getlantern/firetweet/issues/44
=> Support multiple analytics tracking codes

installer-resources/windows/lantern.nsi
Resolvers https://github.com/getlantern/lantern/issues/2477
Oh I can't package windows installer for testing due to lack of BNS_CERT_PASS. Who has interest please test and revise directly.
=> uninstall previous version before install new one

src/github.com/getlantern/balancer/balancer.go, src/github.com/getlantern/balancer/balancer_test.go, src/github.com/getlantern/balancer/dialer.go
Tested against https://github.com/getlantern/lantern/pull/2524#issuecomment-102423632, panic disappears.
=> Use separate channel to close balancer dialer fixes #2500

src/github.com/getlantern/flashlight/logging/logging.go, src/github.com/getlantern/flashlight/util/http.go
Also added timeouts to the transport.
=> Change to not use persistent connections by default closes #2491

src/github.com/getlantern/analytics/analytics.go, src/github.com/getlantern/flashlight/analytics/analytics.go, src/github.com/getlantern/flashlight/flashlight.go, src/github.com/getlantern/flashlight/util/http.go, src/github.com/getlantern/lantern-android/client/client.go
OK this changes the analytics calls to not use DDF.
=> Don't use direct domain fronting for analytics closes #2540

src/github.com/getlantern/flashlight/logging/logging.go
Removed another WaitForServer call while we're at it.
=> don't wait for server since that's handled elsewhere #2548

src/github.com/getlantern/lantern-android/client/client.go, src/github.com/getlantern/lantern-android/client/client_test.go, src/github.com/getlantern/lantern-android/client/config.go
Use getlantern/golog instead of log package and use Errorf instead of Fatalf
=> Fix for getlantern/firetweet#86

src/github.com/getlantern/tarfs/tarfs.go
Fixes https://github.com/getlantern/lantern/issues/2552
=> resolve ambiguity in tarfs

src/github.com/getlantern/flashlight/autoupdate/autoupdate.go
Closes https://github.com/getlantern/lantern/issues/2484
=> Fixing wrong log level

src/github.com/getlantern/analytics/analytics.go
1. Removed unused vars
2. Adjust log format
3. Rename `SessionEvent` to private `sessionEvent`
4. Don't call `sessionEvent` if no HTTP client created
=> code review suggestions

src/github.com/getlantern/balancer/balancer.go, src/github.com/getlantern/enproxy/conn_impl.go, src/github.com/getlantern/flashlight/client/chained.go, src/github.com/getlantern/fronted/dialer.go
Didn't fix anything, but would be helpful to spot dynamic behaviour of Lantern client.
=> more informative logging

src/github.com/getlantern/flashlight/settings/settings.go, src/github.com/getlantern/flashlight/ui/service.go, src/github.com/getlantern/flashlight/ui/ws.go
Some logging additions as well. Will flag the appropriate couple of lines.
=> Changed to keep reading from UI in the event of a single failure #2480

Dockerfile, Makefile, README.md
See: https://github.com/getlantern/lantern/issues/2552
=> Patch for Go mobile on recent docker versions

src/github.com/getlantern/appdir/appdir_linux.go, src/github.com/getlantern/appdir/appdir_stub.go, src/github.com/getlantern/flashlight/config/config.go
Changing appdir to make an special case for Linux.
See https://github.com/getlantern/lantern/issues/2604
=> Closes #2604

src/github.com/getlantern/flashlight/logging/logging.go, src/github.com/getlantern/flashlight/logging/logging_test.go
Hey @fffw can you review this? I'd like to add it as a hotfix for beta6!
=> Fixed log message length for loggly grouping closes #2650

Makefile
I just knocked this out while releasing beta 6. Can you review @xiam?
=> Added putting beta releases in GitHub as well closes #2633

src/github.com/getlantern/flashlight/flashlight.go
A hot fix to reveal the cause of https://github.com/getlantern/lantern/issues/2647
=> close logging until last minute to log more messages to file

src/github.com/getlantern/flashlight/genconfig/cloud.yaml, src/github.com/getlantern/flashlight/genconfig/cloud.yaml.tmpl, src/github.com/getlantern/flashlight/genconfig/genconfig.go, src/github.com/getlantern/lantern-android/client/client.go, src/github.com/getlantern/lantern-android/client/config.go, src/github.com/getlantern/lantern-android/libflashlight/bindings/main.go
We store the latest version of FireTweet in the cloud config to compare against the version currently running on a user's device to determine whether or not the available update notification is presented.
=> Add latest version of FT to cloud config

src/github.com/getlantern/lantern-ui/app/_css/app.css, src/github.com/getlantern/lantern-ui/app/_css/bookmark.css, src/github.com/getlantern/lantern-ui/app/partials/bookmarks.html, src/github.com/getlantern/lantern-ui/app/partials/footer.html
- Remove blue border when settings icon is clicked
- Remove drop shadow text in tiles
- Lantern logo links to https://getlantern.org
=> UI improvements

src/github.com/getlantern/lantern-ui/app/index.html
Quick fix for https://github.com/getlantern/lantern/issues/2736
=> Restore code to display notification when Lantern is gone

src/github.com/getlantern/flashlight/logging/logging.go
To resolve https://github.com/getlantern/lantern/issues/2735.
An alternative to https://github.com/getlantern/lantern/pull/2754
=> Add running time to log messages

Makefile, src/github.com/getlantern/flashlight/flashlight.go, src/github.com/getlantern/flashlight/logging/logging.go, src/github.com/getlantern/flashlight/settings/settings.go, src/github.com/getlantern/lantern-android/client/client.go, src/github.com/getlantern/lantern-android/libflashlight/make.bash, src/github.com/getlantern/lantern-ui/app/js/services.js, src/github.com/getlantern/lantern-ui/dist/js/app.js
The `revisionDate` value will hold the date and time of the latest commit in `HEAD`.
The old `buildDate` value is still around because it *might* provide useful extra information, but in most cases it was just replaced by `revisionDate`
Closes https://github.com/getlantern/lantern/issues/2753
=> Introducing revision date

Makefile
=> Explicitly setting ACL after promoting "beta" release to "production"

Makefile, README.md
Hey @myleshorton,
I think this can help us to have less noise in the releases creation cycle. Could you take a look?
=> Removing TAG variable. Use VERSION instead. Closes #2795

src/github.com/getlantern/analytics/analytics.go, src/github.com/getlantern/analytics/analytics_test.go, src/github.com/getlantern/lantern-ui/app/js/services.js
Resolves https://github.com/getlantern/lantern/issues/2788
=> Fix client analytics

src/github.com/getlantern/balancer/balancer.go
Just tweaked logs in balancer a bit to help with debugging connection issues.
=> More logs closes #2798

src/github.com/getlantern/lantern-ui/app/_css/app.css
To resolve https://github.com/getlantern/lantern/issues/2740
=> Fix footer at bottom of UI landing page

src/github.com/getlantern/flashlight/util/http.go
This is a pretty big bug. Basically on startup, we wouldn't actually wait for the localhost proxy to be available before trying to use it. This would result in errors like:
```
Jul 25 20:12:54.692 - 0m3s ERROR autoupdate: autoupdate.go:97 Problem checking for update: Problem fetching update: Post https://update.getlantern.org/update: http: error connecting to proxy http://localhost:8787: dial tcp 127.0.0.1:8787: ConnectEx tcp: No connection could be made because the target machine actively refused it.
```
=> Fixed loopback check to consider localhost to be loopback closes #2817

src/github.com/getlantern/multicast/multicast_test.go
=> Handle pending messages in Multicast Testing

src/github.com/getlantern/golog/golog.go
Together with TRACE=true, it's very handy for debugging, especially running test.
=> golog to print stack when PRINT_STACK=true

src/github.com/getlantern/flashlight/ui/ws.go
=> Close websocket connections after an error in UI server

src/github.com/getlantern/flashlight/flashlight.go
Closes #2846 
Run the server in a goroutine, so it plays nicely with cleanup/signal-handling code.
=> Closes #2846

src/github.com/getlantern/autoupdate-server/server/server.go
I noticed a typo in one of my comments, sorry.
=> Fixing a typo.

testpackages.txt
=> Do not test cfr package, because it fails due to CloudFront deactivation

README.md, git-hook
Closes https://github.com/getlantern/lantern/issues/2787.
It is not perfect yet, and it won't allow any code to be pushed at the moment since our code doesn't pass through all the tests yet. However, as I progress in this code sanitization, it will become practical to use.
It tries to keep running time minimal by testing only packages that have changed since last commit.
I will keep informed.
=> Git hook (closes #2787)

git-hook
=> fix git hook

src/github.com/getlantern/flashlight/packaged/packaged.go
Merging changes from release-2.0.0+stable back into valencia
=> Release 2.0.0+stable

src/github.com/getlantern/analytics/analytics.go, src/github.com/getlantern/flashlight/analytics/analytics.go, src/github.com/getlantern/flashlight/flashlight.go, src/github.com/getlantern/flashlight/geolookup/geolookup.go, src/github.com/getlantern/flashlight/pubsub/pubsub.go, src/github.com/getlantern/flashlight/pubsub/pubsub_test.go, src/github.com/getlantern/flashlight/server/server.go, src/github.com/getlantern/flashlight/statserver/peer.go, src/github.com/getlantern/geolookup/geolookup.go, src/github.com/getlantern/geolookup/geolookup_test.go, src/github.com/getlantern/lantern-mobile/client.go, testpackages.txt
This is necessary to get accurate geo data in analytics.
=> Override the IP address sent to analytics closes #2922

Makefile
Can you take a quick peek @xiam? This is a quickie.
=> Closes #2929

src/github.com/getlantern/autoupdate-server/main.go, src/github.com/getlantern/autoupdate-server/server/github_test.go, src/github.com/getlantern/autoupdate-server/server/server.go
I discovered this one while testing the auto-update server. Some 9999.99.99 development versions where "upgraded" to 2.0.0+stable.
=> Issue 2944

src/github.com/getlantern/enproxy/proxy.go, src/github.com/getlantern/enproxy/proxy_test.go, src/github.com/getlantern/flashlight/server/server.go, src/github.com/getlantern/flashlight/server/server_test.go, testpackages.txt
I just went ahead and implemented the server side of this since it's really straightforward. You want to take a look @aranhoide?
=> Report and use IP and country from CloudFlare closes #2941

src/github.com/getlantern/flashlight/client/handler.go
Closes #2429 
This tries to respond OK to client application concurrently to outbound connection being established. Should avoid applications timing out because of balancer taking too long to provide a working dialer.
Should we finally add to the loggly message the time taken to fail if it errors? ([see here](https://github.com/getlantern/lantern/issues/2429#issuecomment-130730742))
=> Respond OK to application ASAP when using CONNECT

src/github.com/getlantern/balancer/balancer.go, src/github.com/getlantern/chained/dialer.go, src/github.com/getlantern/flashlight/client/chained.go
Just improves our logging a bit.
=> Adding chained server info to error logs closes #2960

src/github.com/getlantern/flashlight/flashlight.go
You want to have a look at this one too @uaalto?
=> Use separate copies of http.Client closes #2976

src/github.com/getlantern/detour/detour.go, src/github.com/getlantern/detour/direct_conn.go, src/github.com/getlantern/detour/whitelist.go
Hey @fffw, just a few trivial fixes for your detour changes. Care to take a look?
Thanks.
=> Issue2470 suggestions

src/github.com/getlantern/flashlight/geolookup/geolookup.go, src/github.com/getlantern/flashlight/geolookup/geolookup_test.go, src/github.com/getlantern/flashlight/server/server.go
Can someone have a look at this, maybe you @uaalto? It just skips our whole geolookup althogether, although now I'm realizing I need to add this in more places -- still work to do! Don't review yet!
=> use new ip and country headers closes #2943

src/github.com/getlantern/flashlight/logging/logging.go
=> Closes #3019

src/github.com/getlantern/osversion/osversion_linux.go
=> Fix type issue with ARM Uname syscall

src/github.com/getlantern/flashlight/ui/ui.go
Merging into release branch instead.
=> Change to always open new manoto url closes #3025

README.md
Lots of user created issues to seek for help. Hope the links to forums can direct a few of them to there. Feel free to remend/improve my wording.
=> add forum links to README

src/github.com/getlantern/flashlight/client/bootstrap_test.go
Nothing important but good to fix
=> fix bootstrap_test.go

src/github.com/getlantern/flashlight/logging/logging.go, src/github.com/getlantern/flashlight/logging/logging_test.go
Fixes https://github.com/getlantern/lantern/issues/3143
It would be very useful to have Windows user provide logs when submitting issues. So could you have a look at this one @myleshorton?
=> add test for NonStopWriter

src/github.com/getlantern/balancer/balancer.go, src/github.com/getlantern/flashlight/client/reverseproxy.go
Hey @fffw you mind taking a quick peek at this? Just fixes a small issue with initializing Transport.
=> small cleanup closes #3154

.gitignore, Makefile, src/github.com/getlantern/flashlight/flashlight.go, src/github.com/getlantern/lantern-mobile/README.md, src/github.com/getlantern/lantern-mobile/Vagrantfile, src/github.com/getlantern/lantern-mobile/lantern/client.go, src/github.com/getlantern/lantern-mobile/lantern/client_test.go, src/github.com/getlantern/lantern-mobile/lantern/socks-server/main.go, src/github.com/getlantern/lantern-mobile/vagrant-bootstrap.sh, src/github.com/getlantern/lantern-mobile/vagrant-tun-up.sh
Hey @atavism,
Please check this one after https://github.com/getlantern/lantern/pull/3140, tell me so I can rebase this PR.
It includes instructions on how to test the SOCKs server simulating the VpnService API to some extent on a normal Linux vm.
We don't have an easy way to simulate the "protected" call, so I am using the routing table directly.
This is similar to what I did for https://github.com/getlantern/tunio
=> Lantern mobile testing

src/github.com/getlantern/detour/detour.go, src/github.com/getlantern/detour/detour_test.go
Fixes https://github.com/getlantern/lantern/issues/3184
@atavism Could you take a look and help to build a new binary of Lantern Android? This causes frequent crash during my test.
=> Implement LocalAddr() and RemoteAddr() for detour

src/github.com/getlantern/flashlight/client/handler.go, src/github.com/getlantern/flashlight/config/config.go, src/github.com/getlantern/flashlight/flashlight.go, src/github.com/getlantern/fronted/direct.go, src/github.com/getlantern/fronted/direct_test.go, src/github.com/getlantern/geolookup/geolookup_test.go
This is to remove deadlock during config update
=> remove deadlock

src/github.com/getlantern/flashlight/client/handler.go, src/github.com/getlantern/flashlight/client/handler_test.go, src/github.com/getlantern/flashlight/flashlight_test.go
@myleshorton It would be good to also including this fix in new release.
=> respond bad gateway correctly fixes #3159

Makefile
It's a rather simple fix. Sounds good @atavism ?
=> fix incorrect path in Makefile

src/github.com/getlantern/flashlight/config/config.go, src/github.com/getlantern/lantern-mobile/config.go, src/github.com/getlantern/yamlconf/yamlconf.go
Would be cool to get this into 2.0.10!!
=> Just removed file polling closes #3207

src/github.com/getlantern/flashlight/settings/settings.go, src/github.com/getlantern/flashlight/settings/settings_test.go
Trivial code review suggestion for https://github.com/getlantern/lantern/pull/3269
=> not persist versions

src/github.com/getlantern/flashlight/util/http.go
I think this is a little more readable and straightforward @fffw. What do you think?
=> Cleaner approach to dual fetching closes #3315

src/github.com/getlantern/lantern-mobile/Dockerfile
Should be a quick one, could you give a look @uaalto?
=> Updating Dockerfile, gomobile was failing

.travis.yml, Makefile
Resolves #3354 
@xiam mind take a quick look?
=> remove dependency of gtk packages in travis

src/github.com/getlantern/flashlight/flashlight.go
It's a very useful debug tool.
=> add pprofaddr option resolves #3291

src/github.com/getlantern/flashlight/client/chained.go, src/github.com/getlantern/flashlight/client/reverseproxy.go, src/github.com/getlantern/flashlight/settings/settings.go
hey @myleshorton @fffw can you take a look at this when you have a chance, please? In the servers, the idea is that this field won't be mandatory, but we will only get usage statistics from those who provide it.
=> Add permanent ID

src/github.com/getlantern/flashlight/pac.go
=> return DIRECT for non-HTTP url in PAC

Dockerfile, Makefile
See https://github.com/getlantern/lantern/issues/3371
=> Updating Dockerfile to use go1.5

src/github.com/getlantern/lantern-ui/app/locale/en_US.json, src/github.com/getlantern/lantern-ui/app/partials/bookmarks.html, src/github.com/getlantern/lantern-ui/app/partials/modals.html
=> Issue 3460

Dockerfile, src/github.com/getlantern/badserver/badserver.go, src/github.com/getlantern/balancer/balancer.go, src/github.com/getlantern/flashlight/client/chained.go, src/github.com/getlantern/flashlight/client/client.go, src/github.com/getlantern/flashlight/client/handler.go, src/github.com/getlantern/flashlight/client/reverseproxy.go
This requires a PR for servers to get deployed first so that they can handle multiple auth tokens - https://github.com/getlantern/http-proxy-lantern/pull/28
=> Reusing ReverseProxy

README.md
=> added link for Arch Linux binary package

.gitignore, Makefile, src/github.com/getlantern/lantern-ui/app/index.html, src/github.com/getlantern/lantern-ui/app/js/constants.js, src/github.com/getlantern/lantern-ui/app/js/controllers.js, src/github.com/getlantern/lantern-ui/app/js/revision.js, src/github.com/getlantern/lantern-ui/app/js/services.js
Should take care of the Ad not showing when updating a previous installation of Lantern.
=> Issue 3513

src/github.com/getlantern/lantern-mobile/app/build.gradle, src/github.com/getlantern/lantern-mobile/app/proguard-rules.pro
To generate a signed release APK, define ``KEYSTORE_PWD`` and ``KEY_PWD`` in gradle.properties, copy the keystore file to the app directory then run ``gradle clean assembleRelease``
=> Gradle config updates to generate signed release APK

src/github.com/getlantern/lantern-ui/app/_css/app.css, src/github.com/getlantern/lantern-ui/app/js/controllers.js
Closes https://github.com/getlantern/lantern/issues/3546
=> Removing IE cross mark and adding a regex to check e-mail address.

.gitignore, Makefile, README.md
Closes getlantern/lantern#3532
=> Added lantern target that includes race detection

src/github.com/getlantern/lantern-ui/app/js/app.js, src/github.com/getlantern/lantern-ui/app/js/services.js
=> Wrapping window.ga on a function

src/github.com/getlantern/lantern-ui/app/js/services.js
We missed a parameter here, that's why this wasn't working.
=> Closes #3583

src/github.com/getlantern/flashlight/main/pac.go
Or the UI with special domain will not work correctly.
@xiam do you want to have a quick look?
=> allow ws(s):// in pac file resolves #3653

src/github.com/getlantern/geolookup/geolookup.go
Closes https://github.com/getlantern/lantern/issues/3614
=> Making geolocation error less verbose

.gitignore, Makefile, README.md, src/github.com/getlantern/flashlight/ui/resources.go, src/github.com/getlantern/lantern-ui/gulpfile.js, src/github.com/getlantern/lantern-ui/package.json
@xiam @myleshorton This PR allows us to use docker or not, depending on an environment variable.
This isn't finished yet, but the basic concept is in place.  I'm going to pivot to higher priority stuff and revisit this later.
As a side-effect, this closes #3637.
=> Make Docker optional

Makefile
=> Fixed lantern target

src/github.com/getlantern/flashlight/client/client.go, src/github.com/getlantern/flashlight/main/main.go, src/github.com/getlantern/flashlight/main/pac.go, src/github.com/getlantern/flashlight/main/settings.go
Basically the change is to generate the PAC file dynamically based on the current value of ProxyAll.
=> Dynamically serving PAC file closes #3689

src/github.com/getlantern/flashlight/main/main.go, src/github.com/getlantern/flashlight/main/settings.go
You want to take a look at this one @oxtoacart?
=> Changed to save settings to disk when they change closes #3702 and closes #3704

Makefile
Tiny fix closes #3712 -- I'll just merge it.
=> changes from @oxtoacart closes #3712

Makefile
Small tweak for automatically including android in releases. You want to take a look @oxtoacart?
=> make android along with packages closes #3630

src/github.com/getlantern/detour/detect.go
Resolves #3609.
We were too rigid on detecting the symptom of being blocked. In this specific case, due to recent changes of Go library code, `Read` returns `read: connection reset by peer` error instead of previous one `ECONNRESET ` (`connection reset by peer`), which makes `detour` failed to detect. This bug should affect lots of sites, so it probably worth adding to this release.
@myleshorton How do you think?
=> Treat all net.OpError as being blocked

src/github.com/getlantern/detour/detour.go
This doesn't necessarily resolve #3477, but it fixes a panic that I encountered while testing it.
=> Checking for nil connection in detour before closing

src/github.com/getlantern/flashlight/localdiscovery/localdiscovery.go, src/github.com/getlantern/flashlight/main/main.go, src/github.com/getlantern/flashlight/main/settings.go, src/github.com/getlantern/flashlight/proxiedsites/proxiedsites.go, src/github.com/getlantern/flashlight/ui/envelope.go, src/github.com/getlantern/flashlight/ui/proxy.go, src/github.com/getlantern/flashlight/ui/ui.go, src/github.com/getlantern/flashlight/ui/ws.go, src/github.com/getlantern/lantern-ui/app/js/app.js, src/github.com/getlantern/lantern-ui/app/js/controllers.js, src/github.com/getlantern/lantern-ui/app/js/services.js, src/github.com/getlantern/lantern-ui/app/partials/modals.html, src/github.com/getlantern/proxiedsites/proxiedsites.go
* Format changes to the JSON we were using to communicate between client and backend.
* Removed unused code from the UI.
* Allocating space for `user_id` and `token` to be saved in the settings file.
=> JSON format changes and removing unused UI code

src/github.com/getlantern/detour/detour_test.go, src/github.com/getlantern/flashlight/main/settings.go
Rather simple PR for #3819 
@myleshorton Do you think it's useful?
=> not persist version to settings.yaml resolve #3819

src/github.com/getlantern/flashlight/genconfig/proxiedsites/firefly-blacklist.txt
delete "douyutv.com" from "proxiedsites" #3873
=> delete "douyutv.com" from "proxiedsites" #3873

src/github.com/getlantern/lantern-mobile/app/build.gradle
Super tiny change that resolves https://github.com/getlantern/lantern/issues/3858
=> Issue 3858

src/github.com/getlantern/lantern-ui/app/_css/news.css, src/github.com/getlantern/lantern-ui/app/img/ic_list_black_24px.svg, src/github.com/getlantern/lantern-ui/app/img/ic_list_gray_24px.svg, src/github.com/getlantern/lantern-ui/app/locale/en_US.json, src/github.com/getlantern/lantern-ui/app/partials/feeds.html
=> various newsfeed fixes for #3959

src/github.com/getlantern/lantern-ui/app/_css/news.css, src/github.com/getlantern/lantern-ui/app/js/controllers.js, src/github.com/getlantern/lantern-ui/app/js/directives.js, src/github.com/getlantern/lantern-ui/app/partials/feed.html, src/github.com/getlantern/lantern-ui/app/partials/feeds.html
=> hide thumbnail when fail to load image fix #3981

src/github.com/getlantern/lantern-mobile/app/build.gradle, src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/activity/LanternMainActivity.java, src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/model/UI.java
This resolves https://github.com/getlantern/lantern/issues/4056 and https://github.com/getlantern/lantern/issues/4055
=> Issue 4056

src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/model/GetFeed.java, src/github.com/getlantern/lantern-mobile/app/src/main/res/layout/activity_lantern_main.xml, src/github.com/getlantern/lantern-mobile/app/src/main/res/layout/feed_error.xml
This resolves https://github.com/getlantern/lantern/issues/4057
=> Show progress dialog while the news feed loads

README.md, src/github.com/getlantern/lantern-mobile/.idea/compiler.xml, src/github.com/getlantern/lantern-mobile/.idea/modules.xml, src/github.com/getlantern/lantern-mobile/.idea/vcs.xml, src/github.com/getlantern/lantern-mobile/app/app.iml, src/github.com/getlantern/lantern-mobile/build.gradle, src/github.com/getlantern/lantern-mobile/gradle/wrapper/gradle-wrapper.properties
Merging to the release branch because these changes will be helpful when working on other issues with the release.
=> Compatibility with latest Android Studio releases

src/github.com/getlantern/lantern-mobile/app/build.gradle, src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/activity/LanternMainActivity.java, src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/model/GetFeed.java, src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/model/UI.java, src/github.com/getlantern/lantern-mobile/app/src/main/res/layout/activity_lantern_main.xml, src/github.com/getlantern/lantern-mobile/app/src/main/res/layout/feed_error.xml, src/github.com/getlantern/lantern-mobile/app/src/main/res/layout/feed_item.xml, src/github.com/getlantern/lantern/feed.go
This pulls in the mobile feed changes from yesterday that were already merged with devel
https://github.com/getlantern/lantern/pull/4084
https://github.com/getlantern/lantern/pull/4059
https://github.com/getlantern/lantern/pull/4064
=> Mobile feed changes

src/github.com/getlantern/lantern-ui/app/angular-feed/scripts/directives.js, src/github.com/getlantern/lantern-ui/app/angular-feed/scripts/services.js
I also reduced the cache time.
=> Added else to only load the feed if not in the cache closes #4108

src/github.com/getlantern/lantern/feed.go, src/github.com/getlantern/lantern/feed_test.go
@atavism I went ahead and just did this.  Test still passes, plus I added a test for the description issue that I had introduced.
=> Using pointers for Source and FeedItem

src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/activity/LanternMainActivity.java, src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/model/GetFeed.java, src/github.com/getlantern/lantern/feed.go, src/github.com/getlantern/lantern/feed_test.go
This resolves https://github.com/getlantern/lantern/issues/4153 and it also a fixes an issue where we were using "all" instead of the translated string resource for the feed containing every article.
=> Sort feeds on mobile

src/github.com/getlantern/lantern-ui/app/_css/news.css, src/github.com/getlantern/lantern-ui/app/angular-feed/scripts/directives.js, src/github.com/getlantern/lantern-ui/app/js/controllers.js, src/github.com/getlantern/lantern-ui/app/partials/feed.html
It includes fixes to following tickets.
#4145 hide published date if empty
#4117 respect feeds order provided by combinator
#4149 show feed name instead of site url
=> Various 2.2.0 fixes (desktop)

src/github.com/getlantern/lantern-ui/app/_css/news.css, src/github.com/getlantern/lantern-ui/app/angular-feed/scripts/directives.js, src/github.com/getlantern/lantern-ui/app/angular-feed/scripts/services.js, src/github.com/getlantern/lantern-ui/app/js/controllers.js, src/github.com/getlantern/lantern-ui/app/partials/feed.html, src/github.com/getlantern/lantern-ui/app/partials/feeds.html
It includes commits of https://github.com/getlantern/lantern/pull/4155. Merge that PR before looking at this one.
The mixed content happened if the cached feeds differs significantly from the newly fetched feeds. This PR trying to solve it by clean up all existing data when new feeds fetched.
Some time is required to verify if the issue is actually fixed.
=> Another attempt to fix #4108

src/github.com/getlantern/flashlight/analytics/analytics.go, src/github.com/getlantern/flashlight/util/hash.go, src/github.com/getlantern/flashlight/util/util_test.go
Might as well get this into 2.2.0 so we have this data sooner in GA!
=> Added both hash and version reporting closes #4164

src/github.com/getlantern/lantern-ui/app/_css/bookmark.css, src/github.com/getlantern/lantern-ui/app/index.html
@myleshorton It's for Derek's design change at https://github.com/getlantern/lantern/issues/4185#issuecomment-216836492
=> make top right box more subtle when newsfeeds are shown

src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/activity/LanternMainActivity.java
@myleshorton Just curious, does this fix the issue you were seeing with ``Gravity.START`` not existing?
=> Switch to GravityCompat

src/github.com/getlantern/lantern-ui/app/partials/news.html
=> Not loading newsfeed thumbnails unless actually viewing feeds

src/github.com/getlantern/lantern-mobile/app/build.gradle, src/github.com/getlantern/lantern-mobile/app/proguard-rules.pro, src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/activity/LanternMainActivity.java, src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/model/FeedAdapter.java, src/github.com/getlantern/lantern-mobile/app/src/main/res/layout/activity_lantern_main.xml, src/github.com/getlantern/lantern-mobile/app/src/main/res/values-zh-rCN/strings.xml, src/github.com/getlantern/lantern-mobile/build.gradle
Resolves https://github.com/getlantern/lantern/issues/4240 and https://github.com/getlantern/lantern/issues/4235
=> Remove Ion and switch to Glide

src/github.com/getlantern/flashlight/client/client.go, src/github.com/getlantern/flashlight/client/handler.go, src/github.com/getlantern/lantern-mobile/.idea/compiler.xml, src/github.com/getlantern/lantern-mobile/.idea/modules.xml, src/github.com/getlantern/protected/protected.go
This enables mobile to work with proxies that only allow specific ports.
=> Bypassing disallowed ports in SOCKS proxy

Makefile
I already moved the beta installers to overwrite the old qa installers.
=> changed qa name

src/github.com/getlantern/balancer/balancer.go, src/github.com/getlantern/balancer/balancer_test.go, src/github.com/getlantern/chained/dialer.go, src/github.com/getlantern/flashlight/client/client.go, src/github.com/getlantern/flashlight/client/handler.go
=> balancer don't retry same dialer if it was failed

README.md
To push to bitbucket incrementally.
=> Switch main download link to GitLab

README.md
adds translations for Arabic and Farsi
=> add farsi and arabic translations
